version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=lenslocked_user
      - POSTGRES_PASSWORD=lenslocked_password
      - POSTGRES_DB=lenslocked_db
  redis:
    image: redis:3.2
    ports:
      - "63790:6379"
